/**
 * Vayu — every picture the site SHIPS, keyed by the file that is actually
 * served, with its intrinsic size.
 *
 * GENERATED by scripts/images.mjs. Do not edit by hand: the next build
 * overwrites it. Add a picture to public/assets/images and it appears here.
 *
 * KEYED ON THE .avif, which is the thing to understand before changing
 * anything that reads this. The site used to ship a PNG or JPEG and offer an
 * AVIF twin beside it, so the manifest was keyed on the source and carried
 * an `avif: true` flag. That made 39MB of sources load-bearing: they were
 * the <img> fallback, and the manifest could not be built without them.
 *
 * The sources are gone. The AVIF is the picture now, and every entry here
 * describes the bytes a browser receives. The cost is that there is no
 * fallback format: a browser too old for AVIF (Safari before 16.4) sees
 * nothing. That was a deliberate trade for 94% of the image weight.
 *
 * Code still refers to pictures by their ORIGINAL names — '…/hero.jpg' —
 * because those strings are spread across markup, content modules and rows
 * in D1 that no build step can rewrite. `shippedAvif` below does the
 * translation, so a caller passes the name it has always used and gets the
 * file that exists.
 *
 * `w`/`h` are what the <img> width and height attributes carry — not a
 * display size, the file's own. They reserve the right box before the bytes
 * arrive, which is what stops the page jumping as it loads. An AVIF has the
 * same pixel dimensions as the file it was made from, so these numbers did
 * not change when the sources went.
 */

export const IMAGE_SIZES = {
    '/assets/images/banner_decor_21_9.avif': { w: 2100, h: 900 },
    '/assets/images/banner_fashion_32_9.avif': { w: 1966, h: 800 },
    '/assets/images/banner_furniture_21_9.avif': { w: 2100, h: 900 },
    '/assets/images/banner_home_21_9.avif': { w: 2100, h: 900 },
    '/assets/images/banner_materials_21_9.avif': { w: 2100, h: 900 },
    '/assets/images/black_lamp.avif': { w: 768, h: 1024 },
    '/assets/images/cat_apparel.avif': { w: 1024, h: 1024 },
    '/assets/images/cat_art.avif': { w: 1024, h: 1024 },
    '/assets/images/cat_furniture.avif': { w: 1024, h: 1024 },
    '/assets/images/cat_jewelry.avif': { w: 1024, h: 1024 },
    '/assets/images/cat_objects.avif': { w: 1024, h: 1024 },
    '/assets/images/cat_tableware.avif': { w: 1024, h: 1024 },
    '/assets/images/cat_textiles.avif': { w: 1024, h: 1024 },
    '/assets/images/curated_decor.avif': { w: 1024, h: 1024 },
    '/assets/images/curated_fashion.avif': { w: 1024, h: 1024 },
    '/assets/images/curated_furniture.avif': { w: 1024, h: 1024 },
    '/assets/images/curated_home.avif': { w: 1024, h: 1024 },
    '/assets/images/curated_materials.avif': { w: 1024, h: 1024 },
    '/assets/images/gallery_hero.avif': { w: 1024, h: 1024 },
    '/assets/images/gallery_tile1.avif': { w: 1024, h: 576 },
    '/assets/images/gallery_tile2.avif': { w: 1024, h: 1024 },
    '/assets/images/gallery_tile3.avif': { w: 1024, h: 1024 },
    '/assets/images/hero.avif': { w: 1024, h: 438 },
    '/assets/images/jenjum_gadi.avif': { w: 1024, h: 438 },
    '/assets/images/journal_ceramics.avif': { w: 1024, h: 1024 },
    '/assets/images/journal_craft_heritage.avif': { w: 1024, h: 1024 },
    '/assets/images/journal_hero.avif': { w: 1024, h: 1024 },
    '/assets/images/journal_mindful_spaces.avif': { w: 1024, h: 1024 },
    '/assets/images/journal_nyt_press.avif': { w: 1024, h: 1024 },
    '/assets/images/journal_weaving.avif': { w: 1024, h: 1024 },
    '/assets/images/makers.avif': { w: 428, h: 210 },
    '/assets/images/personal_heirlooms.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_brass_cuff.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_brass_shiva_head.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_cane_side_table.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_ceramic_plate_set.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_chair.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_console_table.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_crimson_floor_lamp.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_grey_pattern_shirt.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_lamp.avif': { w: 232, h: 240 },
    '/assets/images/prod_linen_kurta.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_lotus_urli_lamp.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_murano_glassware.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_silk_stole.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_stone_coffee_table.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_striped_jacket.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_teak_chair.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_terracotta_vase.avif': { w: 1024, h: 1024 },
    '/assets/images/prod_wool_shawl.avif': { w: 1024, h: 1024 },
    '/assets/images/summer_cut.avif': { w: 1672, h: 941 },
};

/** Strip any query and swap the extension for .avif. */
const asAvif = (src) => String(src || '').split('?')[0].replace(/\.(png|jpe?g)$/i, '.avif');

/**
 * The file to actually serve for a picture referred to by any of its names,
 * or '' when this is not a shipped picture at all.
 *
 * Falls back to the path as given when there is no AVIF but the file itself
 * is in the manifest — that is the rare source which encoded larger as AVIF
 * and was left as it was.
 */
export function shippedAvif(src) {
    const avif = asAvif(src);
    if (IMAGE_SIZES[avif]) return avif;
    const clean = String(src || '').split('?')[0];
    return IMAGE_SIZES[clean] ? clean : '';
}

/** The dimensions of a shipped picture, or null for anything else. */
export function shippedSize(src) {
    const resolved = shippedAvif(src);
    return resolved ? IMAGE_SIZES[resolved] : null;
}
