/**
 * Vayu — bundle the standalone Workers.
 *
 * The storefront is a SvelteKit project and is emitted by
 * adapter-cloudflare (scripts/build.mjs). The other apps in the split are
 * plain Workers with a single fetch handler, so they are bundled here with
 * esbuild instead — one output per app, each one self-contained.
 *
 *   node scripts/build-workers.mjs            build every app
 *   node scripts/build-workers.mjs api        build one
 *
 * Output goes to .workers/<app>/worker.js, which each app's wrangler config
 * points `main` at. That directory is disposable: it is rebuilt from source
 * every time and is gitignored.
 *
 * Why `platform: 'neutral'` and not 'node': workerd is neither a browser nor
 * Node. Neutral with the workerd/worker conditions picks the right branch of
 * any package that ships several, and leaves `node:*` imports alone for the
 * runtime's own nodejs_compat layer to satisfy.
 */

import { build } from 'esbuild';
import { rmSync, mkdirSync, readdirSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outRoot = path.join(root, '.workers');

/**
 * A virtual module holding the admin panel's own files.
 *
 * The monolith got these from Vite's `import.meta.glob(..., { query: '?raw' })`,
 * which esbuild has no equivalent for — both `import.meta.glob` and the
 * `?raw` suffix are Vite features, and an esbuild bundle of the admin app
 * fails on them outright. This plugin does the same job at build time:
 * `import FILES from 'virtual:admin-ui'` yields { "views/catalog.js": "…" }.
 *
 * The files must be bundled rather than served as static assets. Workers
 * Assets short-circuits to env.ASSETS.fetch BEFORE the Worker's own routing
 * runs, so a panel file published as an asset is handed to anyone who asks
 * for it by path and the session gate never executes.
 */
const adminAssets = {
  name: 'vayu-admin-assets',
  setup(b) {
    b.onResolve({ filter: /^virtual:admin-ui$/ }, () => ({
      path: 'virtual:admin-ui',
      namespace: 'vayu-virtual',
    }));

    b.onLoad({ filter: /.*/, namespace: 'vayu-virtual' }, () => {
      const base = path.join(root, 'app', 'admin-ui');
      const files = {};

      const walk = (dir) => {
        for (const entry of readdirSync(dir)) {
          const full = path.join(dir, entry);
          if (statSync(full).isDirectory()) { walk(full); continue; }
          // Forward slashes: the key is matched against a URL path, not a
          // filesystem path, and this build runs on Windows.
          const key = path.relative(base, full).split(path.sep).join('/');
          files[key] = readFileSync(full, 'utf8');
        }
      };
      walk(base);

      // Modules the panel shares with the storefront. The panel ships as
      // source rather than a bundle, so a bare "#lib/" specifier inside one
      // of its files would reach the browser unresolved — anything both
      // sides need is re-exposed under /admin/shared/ instead.
      files['shared/options.js'] = readFileSync(
        path.join(root, 'app', 'lib', 'options.js'), 'utf8',
      );

      return { contents: `export default ${JSON.stringify(files)};`, loader: 'js' };
    });
  },
};

/**
 * The apps that are plain Workers.
 *
 * The storefront is deliberately absent — it is SvelteKit, its entry is
 * generated by the adapter, and bundling it here would produce a second
 * Worker that shadows the real one.
 */
const APPS = {
  api: 'apps/api/worker.js',
  admin: 'apps/admin/worker.js',
  payments: 'apps/payments/worker.js',
};

const only = process.argv[2];
const targets = only ? { [only]: APPS[only] } : APPS;

if (only && !APPS[only]) {
  console.error(`unknown app "${only}". Known: ${Object.keys(APPS).join(', ')}`);
  process.exit(1);
}

for (const [name, entry] of Object.entries(targets)) {
  const outdir = path.join(outRoot, name);
  rmSync(outdir, { recursive: true, force: true });
  mkdirSync(outdir, { recursive: true });

  try {
    const result = await build({
      entryPoints: [path.join(root, entry)],
      outfile: path.join(outdir, 'worker.js'),
      bundle: true,
      format: 'esm',
      platform: 'neutral',
      target: 'es2022',
      // workerd first: a package that ships a Workers build should give us
      // that one rather than its browser or Node branch.
      conditions: ['workerd', 'worker', 'browser', 'import', 'default'],
      mainFields: ['module', 'main'],
      // Left to the runtime: `cloudflare:*` is built in, and `node:*` is
      // provided by the nodejs_compat flag each config sets.
      external: ['cloudflare:*', 'node:*'],
      plugins: [adminAssets],
      logLevel: 'silent',
      metafile: true,
    });

    const bytes = Object.values(result.metafile.outputs)[0]?.bytes ?? 0;
    console.log(`  ${name.padEnd(9)} ${(bytes / 1024).toFixed(1).padStart(7)} kB  ${entry}`);
  } catch (err) {
    console.error(`\nbuild failed: ${name} (${entry})\n`);
    for (const e of err.errors ?? []) {
      const at = e.location ? `${e.location.file}:${e.location.line}` : '';
      console.error(`  ${e.text}${at ? `  [${at}]` : ''}`);
    }
    process.exit(1);
  }
}

console.log('workers built');
