/**
 * Vayu — pull the webfonts down from Google and self-host them.
 *
 * Run once (`npm run fonts`); the .woff2 files and the generated @font-face
 * block are committed. Re-run only to add a weight or to pick up a new
 * upstream version.
 *
 * Why: loading them from Google costs two extra origins and two levels of
 * request chaining — the document asks fonts.googleapis.com for a
 * stylesheet, and only once *that* has parsed does the browser learn the
 * fonts.gstatic.com URLs it actually needs. Self-hosted, the @font-face
 * rules are already in css/styles.css, which the document requests
 * directly, so the faces start downloading a level earlier and on a
 * connection that is already open.
 *
 * Cormorant Garamond, Jost and Pinyon Script are all under the SIL Open
 * Font License, which permits redistribution — so serving them from our own
 * origin is fine.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(root, 'public', 'assets', 'fonts');

/** A modern UA, or Google serves the .ttf fallback stylesheet instead. */
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

/**
 * Exactly the faces css/styles.css asks for, and no more. `slug` becomes the
 * filename; `latin` and `latin-ext` are the only subsets kept — the site is
 * English, and latin-ext is what carries the rupee sign (U+20B9) that every
 * price is written with.
 */
const FACES = [
    { family: 'Jost', weight: 300, style: 'normal', slug: 'jost-300' },
    { family: 'Jost', weight: 400, style: 'normal', slug: 'jost-400' },
    { family: 'Jost', weight: 500, style: 'normal', slug: 'jost-500' },
    { family: 'Cormorant Garamond', weight: 300, style: 'normal', slug: 'cormorant-garamond-300' },
    { family: 'Cormorant Garamond', weight: 400, style: 'normal', slug: 'cormorant-garamond-400' },
    { family: 'Cormorant Garamond', weight: 500, style: 'normal', slug: 'cormorant-garamond-500' },
    { family: 'Cormorant Garamond', weight: 600, style: 'normal', slug: 'cormorant-garamond-600' },
    { family: 'Cormorant Garamond', weight: 400, style: 'italic', slug: 'cormorant-garamond-400-italic' },
    { family: 'Pinyon Script', weight: 400, style: 'normal', slug: 'pinyon-script-400' },
];

const SUBSETS = ['latin', 'latin-ext'];

function cssUrl({ family, weight, style }) {
    const name = family.replaceAll(' ', '+');
    const axis = style === 'italic' ? `ital,wght@1,${weight}` : `wght@${weight}`;
    return `https://fonts.googleapis.com/css2?family=${name}:${axis}&display=swap`;
}

/** Split Google's stylesheet into `{ subset, url, unicodeRange }` records. */
function parseFaces(css) {
    const out = [];
    const blocks = css.split('/*').slice(1);
    for (const block of blocks) {
        const subset = block.slice(0, block.indexOf('*/')).trim();
        const url = block.match(/src:\s*url\((https:[^)]+\.woff2)\)/)?.[1];
        const range = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
        if (url && range) out.push({ subset, url, unicodeRange: range });
    }
    return out;
}

const fetchText = async (url) => {
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`${url} → ${res.status}`);
    return res.text();
};

await mkdir(OUT, { recursive: true });

const rules = [];

for (const face of FACES) {
    const css = await fetchText(cssUrl(face));
    const parsed = parseFaces(css).filter(f => SUBSETS.includes(f.subset));
    if (!parsed.length) throw new Error(`no latin subset for ${face.slug}`);

    for (const { subset, url, unicodeRange } of parsed) {
        const suffix = subset === 'latin' ? '' : '-ext';
        const file = `${face.slug}${suffix}.woff2`;

        const res = await fetch(url, { headers: { 'User-Agent': UA } });
        if (!res.ok) throw new Error(`${url} → ${res.status}`);
        const bytes = Buffer.from(await res.arrayBuffer());
        await writeFile(path.join(OUT, file), bytes);
        console.log(`  ${(bytes.length / 1024).toFixed(1).padStart(6)} KB  ${file}`);

        rules.push([
            '@font-face {',
            `  font-family: '${face.family}';`,
            `  font-style: ${face.style};`,
            `  font-weight: ${face.weight};`,
            '  font-display: swap;',
            `  src: url('/assets/fonts/${file}') format('woff2');`,
            `  unicode-range: ${unicodeRange};`,
            '}',
        ].join('\n'));
    }
}

const banner = `/* ==========================================================================
   Self-hosted webfonts — generated by scripts/fetch-fonts.mjs, do not edit.

   These used to be three <link>s in every page's <head> pointing at
   fonts.googleapis.com, which then named the real files on
   fonts.gstatic.com: two extra origins to connect to, and the faces could
   not begin downloading until that second stylesheet had arrived and
   parsed. Declaring them here puts them one level earlier in the waterfall,
   on a connection the browser has already opened for this stylesheet.

   Only the latin and latin-ext subsets are kept. latin-ext is not optional:
   it carries U+20B9, the rupee sign every price on the site is written
   with.
   ========================================================================== */

`;

await writeFile(path.join(OUT, 'fonts.css'), banner + rules.join('\n\n') + '\n', 'utf8');
console.log(`\n[vayu] ${rules.length} faces → public/assets/fonts/fonts.css`);
