/**
 * Vayu — import admin/data/db.json into D1.
 *
 * Turns the JSON document store into the rows migration 0001 expects, and
 * writes them out as one SQL file that is then fed to `wrangler d1
 * execute`. Doing it as SQL (rather than a thousand HTTP calls) means the
 * whole import is one transaction: it either lands or it does not.
 *
 *   node scripts/import-db.mjs --local     # the wrangler dev database
 *   node scripts/import-db.mjs --remote    # the deployed one
 *   node scripts/import-db.mjs --sql-only  # just write the .sql and stop
 *
 * Safe to re-run: every statement is an upsert keyed on the natural key,
 * and passwords come across untouched, so existing admin and customer
 * sign-ins keep working.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const DB_JSON = join(root, 'admin', 'data', 'db.json');
// Deliberately NOT in migrations/: wrangler treats every .sql file there as
// a migration, and this is a one-off data load, not a schema step.
const OUT_SQL = join(root, 'scripts', 'import.generated.sql');
const DB_NAME = 'vayu-db';

/* ---------- SQL helpers ---------- */

const lines = [];
const emit = (sql) => lines.push(sql);

/** Quote a value for inline SQL. Numbers and null pass through. */
function q(v) {
  if (v === undefined || v === null) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : '0';
  if (typeof v === 'boolean') return v ? '1' : '0';
  if (typeof v === 'object') return q(JSON.stringify(v));
  return `'${String(v).replaceAll("'", "''")}'`;
}

/** INSERT ... ON CONFLICT DO UPDATE, so a re-run refreshes instead of failing. */
function insert(table, row, conflict) {
  const keys = Object.keys(row);
  const updates = keys.filter(k => !conflict.includes(k))
    .map(k => `"${k}" = excluded."${k}"`).join(', ');
  emit(
    `INSERT INTO "${table}" (${keys.map(k => `"${k}"`).join(', ')}) `
    + `VALUES (${keys.map(k => q(row[k])).join(', ')}) `
    + `ON CONFLICT (${conflict.map(k => `"${k}"`).join(', ')}) DO ${updates ? `UPDATE SET ${updates}` : 'NOTHING'};`,
  );
}

const iso = (v, fallback = new Date().toISOString()) => (v ? String(v) : fallback);

/* ---------- read the source ---------- */

if (!existsSync(DB_JSON)) {
  console.error(`No ${DB_JSON} to import. Nothing to do.`);
  process.exit(1);
}
const db = JSON.parse(readFileSync(DB_JSON, 'utf8'));
const counts = {};
const count = (k, n = 1) => { counts[k] = (counts[k] || 0) + n; };

emit('-- Generated by scripts/import-db.mjs — do not edit by hand.');
emit('PRAGMA foreign_keys = OFF;');

/* ---------- meta and config ---------- */

insert('meta', {
  id: 1,
  version: db.meta?.version ?? 1,
  // Leave room above the highest id already minted, so nextId() cannot
  // collide with an imported one.
  seq: db.meta?.seq ?? 0,
  seeded_at: iso(db.meta?.seededAt),
}, ['id']);

for (const [key, value] of Object.entries(db.settings || {})) {
  insert('config', { scope: 'settings', key, value: JSON.stringify(value), updated_at: iso() }, ['scope', 'key']);
  count('settings');
}
for (const [key, value] of Object.entries(db.content || {})) {
  insert('config', { scope: 'content', key, value: JSON.stringify(value), updated_at: iso() }, ['scope', 'key']);
  count('content');
}

/* ---------- people ---------- */

for (const a of db.admins || []) {
  insert('admins', {
    id: a.id,
    email: String(a.email).toLowerCase(),
    name: a.name || '',
    salt: a.salt,
    hash: a.hash,
    role: a.role || 'owner',
    must_change_password: a.mustChangePassword ? 1 : 0,
    created_at: iso(a.createdAt),
  }, ['id']);
  count('admins');
}

for (const c of db.customers || []) {
  insert('customers', {
    id: c.id,
    email: String(c.email || '').toLowerCase(),
    name: c.name || '',
    phone: c.phone || '',
    address: c.address || '',
    city: c.city || '',
    pin: c.pin || '',
    orders_count: c.ordersCount || 0,
    total_spent: c.totalSpent || 0,
    first_seen: iso(c.firstSeen),
    last_seen: iso(c.lastSeen),
    source: c.source || 'checkout',
    notes: c.notes || '',
    salt: c.salt ?? null,
    hash: c.hash ?? null,
    account_created_at: c.accountCreatedAt ?? null,
  }, ['id']);
  count('customers');

  for (const tag of c.tags || []) insert('customer_tags', { customer_id: c.id, tag }, ['customer_id', 'tag']);

  for (const a of c.addresses || []) {
    insert('addresses', {
      id: a.id,
      customer_id: c.id,
      label: a.label || 'Address',
      name: a.name || '',
      phone: a.phone || '',
      address: a.address || '',
      city: a.city || '',
      pin: a.pin || '',
      is_default: a.isDefault ? 1 : 0,
      created_at: iso(a.createdAt),
    }, ['id']);
    count('addresses');
  }
}

// Sessions are deliberately not imported: cookies are cheap to reissue and
// a migration is a reasonable moment for everyone to sign in again.

/* ---------- catalogue ---------- */

let categoryOrder = 0;
for (const [slug, c] of Object.entries(db.categories || {})) {
  insert('categories', {
    slug,
    title: c.title || slug,
    curated: c.curated || '',
    banner: c.banner || '',
    sort_order: c.order ?? categoryOrder++,
  }, ['slug']);
  count('categories');

  (c.subs || []).forEach((s, i) => insert('category_subs', {
    category_slug: slug,
    label: s.label,
    thumb: s.thumb || '',
    sort_order: i,
  }, ['category_slug', 'label']));
}

let variantSeq = 0;
(db.products || []).forEach((p, index) => {
  insert('products', {
    id: p.id,
    name: p.name,
    description: p.description || '',
    price: p.price || 0,
    compare_at: p.compareAt ?? null,
    sku: p.sku || '',
    stock: p.stock || 0,
    status: p.status || 'active',
    is_new: p.isNew ? 1 : 0,
    img: p.img || '',
    publish_at: p.publishAt ?? null,
    views: p.views || 0,
    sold: p.sold || 0,
    // Position in the JSON array *is* the legacy idx, so it becomes the
    // sort order that keeps every ?cat=&idx= link pointing where it did.
    sort_order: index,
    created_at: iso(p.createdAt),
    updated_at: iso(p.updatedAt),
  }, ['id']);
  count('products');

  for (const c of p.categories || []) {
    insert('product_categories', {
      product_id: p.id, category_slug: c.cat, sub: c.sub || '',
    }, ['product_id', 'category_slug', 'sub']);
  }
  (p.gallery || []).forEach((url, i) => insert('product_gallery', {
    product_id: p.id, url, sort_order: i,
  }, ['product_id', 'url']));
  for (const tag of p.tags || []) {
    insert('product_tags', { product_id: p.id, tag }, ['product_id', 'tag']);
  }
  (p.variants || []).forEach((v, i) => {
    insert('product_variants', {
      id: v.id || `var_import_${++variantSeq}`,
      product_id: p.id,
      label: v.label,
      price: v.price ?? null,
      stock: v.stock || 0,
      sort_order: i,
    }, ['id']);
    count('variants');
  });
});

/* ---------- orders ---------- */

for (const o of db.orders || []) {
  insert('orders', {
    id: o.id,
    number: o.number,
    customer_id: o.customer?.id ?? null,
    name: o.customer?.name || '',
    email: String(o.customer?.email || '').toLowerCase(),
    phone: o.customer?.phone || '',
    address: o.customer?.address || '',
    city: o.customer?.city || '',
    pin: o.customer?.pin || '',
    subtotal: o.subtotal || 0,
    discount: o.discount || 0,
    coupon: o.coupon ?? null,
    shipping: o.shipping || 0,
    total: o.total || 0,
    payment_method: o.payment?.method || 'cod',
    payment_id: o.payment?.paymentId ?? null,
    payment_order_id: o.payment?.orderId ?? null,
    // Orders written before accounts existed were all guest orders.
    guest: o.guest === undefined ? 1 : (o.guest ? 1 : 0),
    status: o.status || 'new',
    created_at: iso(o.createdAt),
  }, ['id']);
  count('orders');

  // Lines and timeline have autoincrement ids, so they are cleared first to
  // keep a re-run from doubling them.
  emit(`DELETE FROM "order_items" WHERE "order_id" = ${q(o.id)};`);
  (o.items || []).forEach((l, i) => emit(
    `INSERT INTO "order_items" ("order_id","product_id","name","price","qty","img","variant","sort_order") `
    + `VALUES (${q(o.id)}, ${q(l.productId ?? null)}, ${q(l.name)}, ${q(l.price || 0)}, `
    + `${q(l.qty || 1)}, ${q(l.img || '')}, ${q(l.variant ?? null)}, ${i});`));

  emit(`DELETE FROM "order_timeline" WHERE "order_id" = ${q(o.id)};`);
  for (const t of o.timeline || []) {
    emit(
      `INSERT INTO "order_timeline" ("order_id","t","status","note") `
      + `VALUES (${q(o.id)}, ${q(iso(t.t))}, ${q(t.status || 'new')}, ${q(t.note || '')});`);
  }
}

/* ---------- coupons ---------- */

for (const c of db.coupons || []) {
  insert('coupons', {
    id: c.id,
    code: c.code,
    type: c.type || 'percent',
    value: c.value || 0,
    min_order: c.minOrder || 0,
    expires_at: c.expiresAt ?? null,
    usage_limit: c.usageLimit || 0,
    per_customer_limit: c.perCustomerLimit || 0,
    active: c.active === false ? 0 : 1,
    used_count: c.usedCount || 0,
    created_at: iso(c.createdAt),
  }, ['id']);
  count('coupons');

  for (const e of c.restrictTo?.emails || []) {
    insert('coupon_restrictions', { coupon_id: c.id, kind: 'email', value: String(e).toLowerCase() },
      ['coupon_id', 'kind', 'value']);
  }
  for (const p of c.restrictTo?.phones || []) {
    insert('coupon_restrictions', { coupon_id: c.id, kind: 'phone', value: String(p) },
      ['coupon_id', 'kind', 'value']);
  }

  emit(`DELETE FROM "coupon_uses" WHERE "code" = ${q(c.code)};`);
  for (const u of c.uses || []) {
    emit(`INSERT INTO "coupon_uses" ("code","email","t") VALUES `
      + `(${q(c.code)}, ${q(String(u.email || '').toLowerCase())}, ${q(iso(u.t))});`);
  }
}

/* ---------- content and signals ---------- */

for (const r of db.reviews || []) {
  insert('reviews', {
    id: r.id,
    product_id: r.productId ?? null,
    product_name: r.productName || '',
    name: r.name || '',
    email: String(r.email || '').toLowerCase(),
    rating: r.rating || 5,
    text: r.text || '',
    status: r.status || 'pending',
    t: iso(r.t),
  }, ['id']);
  count('reviews');
}

(db.journal || []).forEach((s, i) => {
  insert('journal', {
    id: s.id,
    featured: s.featured ? 1 : 0,
    category: s.category || 'craft',
    category_label: s.categoryLabel || '',
    title: s.title || '',
    excerpt: s.excerpt || '',
    date: s.date || '',
    image: s.image || '',
    alt: s.alt || '',
    reading_time: s.readingTime || '',
    body: JSON.stringify(Array.isArray(s.body) ? s.body : []),
    sort_order: i,
  }, ['id']);
  count('journal');
});

for (const s of db.subscribers || []) {
  insert('subscribers', {
    email: String(s.email).toLowerCase(), t: iso(s.t), source: s.source || 'footer',
  }, ['email']);
  count('subscribers');
}

for (const a of db.stockAlerts || []) {
  insert('stock_alerts', {
    product_id: a.productId,
    email: String(a.email).toLowerCase(),
    notified: a.notified ? 1 : 0,
    t: iso(a.t),
  }, ['product_id', 'email']);
  count('stockAlerts');
}

for (const m of db.outbox || []) {
  insert('outbox', {
    id: m.id,
    to_addr: m.to,
    subject: m.subject || '',
    body: m.body || '',
    event: m.event || '',
    status: m.status || 'queued',
    t: iso(m.t),
  }, ['id']);
  count('outbox');
}

// Append-only logs: cleared and rewritten, since their ids are generated.
emit('DELETE FROM "inventory_log";');
for (const l of db.inventoryLog || []) {
  emit(`INSERT INTO "inventory_log" ("t","product_id","name","delta","reason","by") VALUES `
    + `(${q(iso(l.t))}, ${q(l.productId ?? null)}, ${q(l.name || '')}, ${q(l.delta || 0)}, `
    + `${q(l.reason || '')}, ${q(l.by || '')});`);
  count('inventoryLog');
}

emit('DELETE FROM "activity";');
for (const a of db.activity || []) {
  emit(`INSERT INTO "activity" ("t","admin","action","detail") VALUES `
    + `(${q(iso(a.t))}, ${q(a.admin || '')}, ${q(a.action || '')}, ${q(a.detail || '')});`);
  count('activity');
}

emit('DELETE FROM "searches";');
for (const s of db.searches || []) {
  emit(`INSERT INTO "searches" ("q","results","sid","t") VALUES `
    + `(${q(s.q || '')}, ${q(s.results || 0)}, ${q(s.sid || '')}, ${q(iso(s.t))});`);
  count('searches');
}

for (const [sid, c] of Object.entries(db.carts || {})) {
  insert('carts', {
    sid, items: JSON.stringify(c.items || []), total: c.total || 0, updated_at: iso(c.t),
  }, ['sid']);
  count('carts');
}

/* ---------- analytics ---------- */

for (const [day, d] of Object.entries(db.analytics?.days || {})) {
  insert('analytics_days', {
    day, views: d.views || 0, atc: d.atc || 0, checkout_start: d.checkoutStart || 0,
  }, ['day']);
  count('analyticsDays');

  for (const [path, n] of Object.entries(d.paths || {})) {
    insert('analytics_paths', { day, path, count: n }, ['day', 'path']);
  }
  for (const [productId, n] of Object.entries(d.products || {})) {
    insert('analytics_products', { day, product_id: productId, count: n }, ['day', 'product_id']);
  }
  for (const sid of Object.keys(d.sids || {})) {
    insert('analytics_visitors', { day, sid }, ['day', 'sid']);
  }
}

emit('DELETE FROM "analytics_recent";');
for (const r of (db.analytics?.recent || []).slice().reverse()) {
  emit(`INSERT INTO "analytics_recent" ("t","path","ref") VALUES `
    + `(${q(iso(r.t))}, ${q(r.path || '/')}, ${q(r.ref || '')});`);
  count('analyticsRecent');
}

emit('PRAGMA foreign_keys = ON;');

/* ---------- write and apply ---------- */

writeFileSync(OUT_SQL, lines.join('\n') + '\n');
console.log(`Wrote ${lines.length} statements to ${OUT_SQL}`);
console.log('Imported:', Object.entries(counts).map(([k, v]) => `${k}=${v}`).join(' '));

const target = process.argv.includes('--remote') ? '--remote' : '--local';
if (process.argv.includes('--sql-only')) {
  console.log(`\nNot applied (--sql-only). To apply:\n  npx wrangler d1 execute ${DB_NAME} ${target} --file ${OUT_SQL}`);
  process.exit(0);
}

console.log(`\nApplying to ${DB_NAME} ${target}…`);
// shell: true because on Windows npx is a .cmd, which Node refuses to
// spawn directly (EINVAL) since the CVE-2024-27980 fix.
execFileSync(
  'npx',
  ['wrangler', 'd1', 'execute', DB_NAME, target, '--file', OUT_SQL, '--yes'],
  { cwd: root, stdio: 'inherit', shell: true },
);
console.log('Done.');
