/**
 * Vayu — rewrite the static fallback from the live shop.
 *
 * The prerendered pages ship with app/lib/data/static-taxonomy.js and
 * static-catalogue.js compiled into them. Those two files are the offline
 * fallback, and they are also the first thing every visitor sees: the
 * document paints them before /api/catalogue has answered. Hand-written and
 * never updated, they had drifted into a shop that does not exist — seven
 * categories where the site has four, products nobody sells — so every
 * visit opened on the wrong catalogue for as long as the fetch took, and a
 * crawler that runs no JavaScript indexed nothing else.
 *
 * The store now paints what the browser saw last time, which fixes the
 * second visit and every one after it. This fixes the first: run it before
 * a deploy and the prerendered HTML ships with the shop as it actually is.
 *
 *   node scripts/snapshot-static.mjs            # the live database
 *   node scripts/snapshot-static.mjs --local    # the one wrangler dev uses
 *   node scripts/snapshot-static.mjs --dry-run  # print, write nothing
 *
 * It shells out to wrangler rather than opening D1 itself, so it uses
 * whatever credentials the machine is already deploying with and there is
 * no second copy of the connection details to keep in step.
 *
 * `idx` — a product's position in its category array — is what
 * /pages/product.html?cat=&idx= addresses, so the order written here is the
 * order the API serves: sort_order, then id. Anything that reorders the
 * catalogue must be followed by another run of this, which is the same rule
 * that has always applied to editing these files by hand.
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

// By path, not by `require.resolve`: wrangler's package.json does not export
// its own bin, so resolving the subpath throws.
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const WRANGLER = join(ROOT, 'node_modules', 'wrangler', 'bin', 'wrangler.js');

const args = new Set(process.argv.slice(2));
const LOCAL = args.has('--local');
const DRY = args.has('--dry-run');
// Somewhere else to write, so a run can be checked — parsed, diffed, read —
// without standing on the files the build compiles in.
const OUT_DIR = [...args].find(a => a.startsWith('--out-dir='))?.slice('--out-dir='.length) || '';
const DB = 'vayuindia-db';

const TAXONOMY_FILE = 'app/lib/data/static-taxonomy.js';
const CATALOGUE_FILE = 'app/lib/data/static-catalogue.js';

/** Run one statement through wrangler and hand back its rows. */
function query(sql) {
    // wrangler's own entry point, run by this node: not `npx`, which is a
    // .cmd on Windows that node 20+ refuses to spawn without a shell, and
    // not a shell either, which re-splits the SQL on its spaces and hands
    // wrangler a dozen unknown arguments instead of one --command.
    const out = execFileSync(process.execPath, [
        WRANGLER, 'd1', 'execute', DB, LOCAL ? '--local' : '--remote',
        '--json', '--command', sql,
    ], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });

    // wrangler prints its banner before the JSON on some versions, so the
    // document is found rather than assumed to start at byte zero.
    const start = out.indexOf('[');
    if (start < 0) throw new Error(`no JSON in wrangler output:\n${out.slice(0, 400)}`);
    const parsed = JSON.parse(out.slice(start));
    const first = Array.isArray(parsed) ? parsed[0] : parsed;
    if (!first?.success) throw new Error(`query failed: ${sql.slice(0, 80)}`);
    return first.results || [];
}

/** A JS string literal, single-quoted, safe for the files we write. */
const str = (s) => `'${String(s ?? '').replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;

/** The banner each generated file carries, so nobody edits one by hand. */
const header = (what, sourceDoc) => `/**
 * Vayu — ${what}.
 *
 * GENERATED by scripts/snapshot-static.mjs from the live database. Do not
 * edit by hand: the next run overwrites it. To change what is in here,
 * change it in the admin panel and run the script again before deploying.
 *
${sourceDoc}
 *
 * Taken ${new Date().toISOString().slice(0, 10)}${LOCAL ? ' from the local database' : ''}.
 */
`;

/* ---------------- taxonomy ---------------- */

function buildTaxonomy() {
    const cats = query('SELECT slug, title, curated, banner FROM categories ORDER BY sort_order, slug');
    const subs = query('SELECT category_slug, label, thumb FROM category_subs ORDER BY sort_order, rowid');
    if (!cats.length) throw new Error('the categories table is empty — refusing to write an empty taxonomy');

    const body = cats.map((c) => {
        const mine = subs.filter(s => s.category_slug === c.slug);
        const subLines = mine.length
            ? mine.map(s => `            { label: ${str(s.label)}, thumb: ${str(s.thumb)} }`).join(',\n')
            : '';
        return `    ${c.slug}: {
        title: ${str(c.title)},
        curated: ${str(c.curated)},
        banner: ${str(c.banner)},
        subs: [${subLines ? `\n${subLines}\n        ` : ''}]
    }`;
    }).join(',\n');

    return `${header('category taxonomy', ` * This is the fallback the prerendered pages paint with and the shape
 * /api/nav returns. \`slug\` is not stored on a sub-category: it is derived
 * from \`label\` by subToSlug, which is the rule the ?sub= parameter uses.`)}
export const staticCategories = {
${body}
};
`;
}

/* ---------------- catalogue ---------------- */

function buildCatalogue() {
    // Only what the storefront serves: a draft's page answers 410, and a
    // fallback that lists one is advertising something nobody can buy.
    const rows = query(`
        SELECT p.id, p.slug, p.name, p.price, p.compare_at, p.img, p.is_new,
               pc.category_slug AS cat, pc.sub AS sub, p.sort_order
          FROM products p
          JOIN product_categories pc ON pc.product_id = p.id
         WHERE p.status = 'active'
         ORDER BY pc.category_slug, p.sort_order, p.id`);
    if (!rows.length) throw new Error('no active products — refusing to write an empty catalogue');

    const gallery = query('SELECT product_id, url FROM product_gallery ORDER BY product_id, sort_order');
    const shotsFor = (id) => gallery.filter(g => g.product_id === id).map(g => g.url);

    // Prices are stored in paise and printed by the storefront; the fallback
    // carries the printed form because that is what the tile renders.
    const money = (n) => `₹ ${Number(n || 0).toLocaleString('en-IN')}`;

    const byCat = new Map();
    for (const r of rows) {
        if (!byCat.has(r.cat)) byCat.set(r.cat, []);
        const shots = shotsFor(r.id);
        byCat.get(r.cat).push(`        {
            id: ${str(r.id)}, slug: ${str(r.slug)}, name: ${str(r.name)}, price: ${str(money(r.price))},${
            r.compare_at ? ` compareAt: ${str(money(r.compare_at))},` : ''}
            img: ${str(r.img)}, sub: ${str(r.sub || '')}${r.is_new ? ', isNew: true' : ''},
            gallery: [${(shots.length ? shots : [r.img]).map(str).join(', ')}]
        }`);
    }

    const body = [...byCat.entries()]
        .map(([cat, items]) => `    ${cat}: [\n${items.join(',\n')}\n    ]`)
        .join(',\n');

    return `${header('shared product catalogue', ` * The live catalogue comes from /api/catalogue; this is what the page
 * paints until that answers, and what it keeps if the answer never comes.
 * \`idx\` in /pages/product.html?cat=&idx= is a product's position in its
 * category array here, so the order is the order the API serves.`)}
export const staticProductData = {
${body}
};
`;
}

/* ---------------- write ---------------- */

const files = [
    [TAXONOMY_FILE, buildTaxonomy()],
    [CATALOGUE_FILE, buildCatalogue()],
];

for (const [file, next] of files) {
    const path = OUT_DIR ? join(OUT_DIR, file.split('/').pop()) : file;
    let current = '';
    try { current = readFileSync(path, 'utf8'); } catch { /* first run */ }

    if (DRY) {
        console.log(`\n=== ${path} (${next.length} bytes, ${next.split('\n').length} lines)`);
        console.log(next.split('\n').slice(0, 24).join('\n'));
        console.log('  …');
        continue;
    }
    if (current === next) {
        console.log(`${path} — already current`);
        continue;
    }
    writeFileSync(path, next);
    console.log(`${path} — written (${next.length} bytes)`);
}

if (DRY) console.log('\n--dry-run: nothing written.');
else console.log('\nBuild and deploy to put this in the prerendered pages.');
